### ISSUE TITLE
Move Sphinx docs to GitHub wiki

### ISSUE THREAD

**Issue by nomicode** [crate/crate-docs-build#14]
atm, we have a number of Sphinx docs regarding stylistic conventions, here: https://github.com/crate/crate-docs-build/tree/master/docs/conventions

we should reserve the Sphinx `docs/` project in this repo for testing purposes only (i.e., to be used when working on the build system and you want to test your changes). the repo itself primarily houses the build system and our automated lint checking stuff

human-readable documentation re standards, processes, conventions, etc., should be moved to the wiki associated with this repo

**Comment by nomicode** [comment]
@matthijskrul I have assigned this to you. is that okay? does this ticket make sense? <3

**Comment by matthijskrul** [comment]
https://github.com/crate/crate-docs-build/wiki/General-Conventions
https://github.com/crate/crate-docs-build/wiki/RST-Guidelines
https://github.com/crate/crate-docs-build/wiki/Screenshot-Guidelines
https://github.com/crate/crate-docs-build/wiki/Writing-Guidelines
